[book]
authors = []
language = "zh"
multilingual = false
src = "src"
title = "高级编码指南"

[build]
build-dir = "public"

[preprocesssor.toc]
command = "./mdbook-toc"
renderer = ["html"]

[output.html]
mathjax-support = true
